add a test for sharing an activity between spaces
Meeds-io/meeds-qa-ui pull request #207
Opened 2023-10-26 12:13 UTC by ahamdi

2023-10-26 12:15 UTC, ahamdi commented
This PR won't work until https://github.com/Meeds-io/social/pull/3097 is merged

2023-10-26 14:06 UTC, rdenarie requested changes

2023-10-26 14:06 UTC, rdenarie commented on src/main/java/io/meeds/qa/ui/pages/SpaceHomePage.java
> +    TextBoxElementFacade spaceSuggesterInput = findTextBoxByXPathOrCSS("(//div[@id='selectDestinationSpaceToShare']//input)[1]");
```suggestion
    TextBoxElementFacade spaceSuggesterInput = findTextBoxByXPathOrCSS("//div[contains(@class,'activitySpaceSuggester')]//input[@type!='hidden']");
```

2026-07-01 07:23 UTC, houssemexo26 commented
This pull request is being closed because the `develop-exo` and `develop-meed` branches are no longer used as integration branches.

Please retarget your changes to the appropriate branch if the change is still relevant.

2026-07-01 07:23 UTC, closed without merging