Send a kudos to someone different from the activity author
Meeds-io/meeds-qa-ui pull request #53
Opened 2022-09-29 17:43 UTC by anisb0026

New Test case:  Send a kudos to someone different from the activity author.

2022-10-05 07:27 UTC, boubaker commented on src/test/resources/features/Kudos/kudos.feature
> +    Then the activity 'Kudos Post activity' is displayed in activity stream
The message `Kudos Post activity` is already used in another scenario, please add a specific message for the newly introduced scenario to not having XPath conflicts when displaying the Stream. (The Kudos may not have been sent here, but it succeeds because the other scenario had already posted exactly the same message)

2022-10-10 17:04 UTC, ichaieb requested changes

2022-10-10 17:04 UTC, ichaieb commented on src/test/resources/features/Kudos/kudos.feature
> +    And I send to the activity 'Bonjour Team' a kudos message 'bien bien bien' to second created user
it is better to use English even in the messages to pass in the step gherkin and of course different from those used in the other scenarios .

2022-10-10 17:04 UTC, ichaieb commented on src/test/resources/features/Kudos/kudos.feature
> +    Then the activity 'Bonjour Team' is displayed in activity stream
it is better to use English even in the messages to pass in the step gherkin

2022-10-10 17:04 UTC, ichaieb commented on src/test/resources/features/Kudos/kudos.feature
> +    And I enter an activity 'Bonjour Team'
it is better to use English even in the messages to pass in the step gherkin

2022-12-12 14:11 UTC, ichaieb requested changes

2022-12-12 14:11 UTC, ichaieb commented on src/main/java/io/meeds/qa/ui/pages/page/factory/Kudos/KudosPage.java
> +  private BaseElementFacade choseAnotherUser(String user)
correct the function name  please "chooseAnotherUser"

2022-12-12 14:11 UTC, ichaieb commented on src/test/resources/features/Kudos/kudos.feature
> +@kudos1
remove the test tag and keep @kudos

2022-12-12 14:11 UTC, ichaieb commented on src/main/java/io/meeds/qa/ui/pages/page/factory/Kudos/KudosPage.java
> +    choseAnotherUser(user).clickOnElement();
correct the function name please "chooseAnotherUser"

2022-12-13 16:00 UTC, ichaieb requested changes

2022-12-13 16:00 UTC, ichaieb commented on src/main/java/io/meeds/qa/ui/pages/page/factory/Kudos/KudosPage.java
> +    choseAnotherUser(user).clickOnElement();
cc @anisb0026

2022-12-23 16:23 UTC, ichaieb approved these changes

2022-12-23 16:29 UTC, merged